name: Build KuroNet
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y cmake g++ libboost-all-dev

      - name: Build
        run: |
          mkdir build && cd build
          cmake ..
          make -j4